---
version: '3'

volumes:
  data:
  conf:
  keystore:
  logs:

services:
  sparkview:
    image: 'beyondssl/sparkview:latest'
    volumes:
      - type: volume
        source: data
        target: /usr/local/bin/SparkGateway/data
      - type: volume
        source: conf
        target: /usr/local/bin/SparkGateway/conf
      - type: volume
        source: keystore
        target: /usr/local/bin/SparkGateway/keystore
      - type: volume
        source: logs
        target: /usr/local/bin/SparkGateway/logs
    ports:
      - '80:80'
      - '443:443'